version: '3.8'

services:
  app:
    image: 'mrapaport/gymcore:v1.0'
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/gymcore"
      SPRING_DATASOURCE_USERNAME: "supersecretuser"
      SPRING_DATASOURCE_PASSWORD: "thisisprobablynotthehardestpasswordintheworld"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: "gymcore"
      POSTGRES_USER: "supersecretuser"
      POSTGRES_PASSWORD: "thisisprobablynotthehardestpasswordintheworld"
    ports:
      - "5423:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
